# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
project 'REST Countries.xcodeproj'

target 'REST Countries' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for REST Countries
  pod 'SVGKit'

end

target 'REST Countries Widget' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for REST Countries Widget
    pod 'SVGKit'
end
