# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'REST Countries' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for REST Countries
  pod 'Alamofire'
  pod 'SVGKit'
  
  target 'REST CountriesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'REST CountriesUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
